Fix: Cannot install sqlite3, because it is already part of the standarf library.
Error was:

ERROR: Could not find a version that satisfies the requirement sqlite3 (from -r requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for sqlite3 (from -r requirements.txt (line 7))

According to https://docs.python.org/3/library/sqlite3.html, it is part of the standard lib.